// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var BroadcasterItem$ReactTemplate = require("../components/BroadcasterItem.bs.js");

var component = ReasonReact.statelessComponent("Example");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("p", undefined, "Do the thing"), React.createElement("h1", undefined, "Speak now or be eternally damned."), React.createElement("ol", undefined, ReasonReact.element(undefined, undefined, BroadcasterItem$ReactTemplate.make(5, /* array */[])), ReasonReact.element(undefined, undefined, BroadcasterItem$ReactTemplate.make(4, /* array */[])), ReasonReact.element(undefined, undefined, BroadcasterItem$ReactTemplate.make(3, /* array */[]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
