// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("LogIn");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "d-flex justify-content-center"
                        }, React.createElement("div", {
                              className: "card d-flex flex-column justify-content-center",
                              style: {
                                background: "#660000",
                                marginTop: "50px",
                                padding: "15px"
                              }
                            }, React.createElement("h1", undefined, "Log In"), React.createElement("form", undefined, React.createElement("div", {
                                      className: "form-group"
                                    }, React.createElement("label", {
                                          htmlFor: "username"
                                        }, "Twitch Username: "), React.createElement("input", {
                                          className: "form-control",
                                          id: "username",
                                          placeholder: "Username"
                                        })), React.createElement("div", {
                                      className: "form-group"
                                    }, React.createElement("label", {
                                          htmlFor: "password"
                                        }, "Twitch Password: "), React.createElement("input", {
                                          className: "form-control",
                                          id: "password",
                                          placeholder: "Password",
                                          type: "password"
                                        })), React.createElement("a", {
                                      className: "nav-link",
                                      style: {
                                        color: "white"
                                      },
                                      href: "dashboard"
                                    }, React.createElement("button", {
                                          className: "btn btn-primary align-self-center",
                                          style: {
                                            background: "#FF6100",
                                            borderColor: "#FF7D2E",
                                            borderRadius: "0"
                                          },
                                          type: "submit"
                                        }, "Log in")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
