// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Broadcaster");

function make(broadcasterObject, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = broadcasterObject[/* id */0] !== "";
              return React.createElement(React.Fragment, undefined, match ? React.createElement("div", {
                                className: "card mb-3",
                                style: {
                                  background: "#660000"
                                }
                              }, React.createElement("img", {
                                    className: "card-img-top",
                                    alt: "...",
                                    src: broadcasterObject[/* profile_image_url */6]
                                  }), React.createElement("div", {
                                    className: "card-body"
                                  }, React.createElement("h5", {
                                        className: "card-title"
                                      }, broadcasterObject[/* display_name */2]), React.createElement("p", {
                                        className: "card-text"
                                      }, "Some quick example text to build on the card title and make up the bulk of the card's content."), React.createElement("a", {
                                        className: "btn btn-primary",
                                        href: "#"
                                      }, "Open modal"))) : React.createElement("div", undefined));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
