// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function decodeJSON(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* login */Json_decode.field("login", Json_decode.string, json),
          /* display_name */Json_decode.field("display_name", Json_decode.string, json),
          /* account_type */Json_decode.field("type", Json_decode.string, json),
          /* broadcaster_type */Json_decode.field("broadcaster_type", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* profile_image_url */Json_decode.field("profile_image_url", Json_decode.string, json),
          /* offline_image_url */Json_decode.field("offline_image_url", Json_decode.string, json),
          /* view_count */Json_decode.field("view_count", Json_decode.$$int, json),
          /* email */Json_decode.field("email", Json_decode.string, json)
        ];
}

function decodeData(json) {
  return /* record */[/* data */Json_decode.field("data", decodeJSON, json)];
}

var Decode = /* module */[
  /* decodeJSON */decodeJSON,
  /* decodeData */decodeData
];

var component = ReasonReact.reducerComponent("Broadcaster");

function make(broadcasterObject, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              fetch("https://api.twitch.tv/helix/users?login=" + Caml_array.caml_array_get(broadcasterObject, 0), Fetch.RequestInit[/* make */0](undefined, {
                              "Client-ID": "re6wrq92zpvgqndlc8mokgr97j09l9"
                            }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                        return prim.json();
                      })).then((function (json) {
                      var json$1 = decodeData(json);
                      return Promise.resolve(Curry._1(self[/* send */3], /* AssignData */[json$1[/* data */0]]));
                    }));
              console.log(self[/* state */1][/* data */0]);
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* data */0][/* id */0] !== "";
              return React.createElement(React.Fragment, undefined, match ? React.createElement("div", {
                                className: "card mb-3",
                                style: {
                                  background: "#660000"
                                }
                              }, React.createElement("img", {
                                    className: "card-img-top",
                                    alt: "...",
                                    src: self[/* state */1][/* data */0][/* profile_image_url */6]
                                  }), React.createElement("div", {
                                    className: "card-body"
                                  }, React.createElement("h5", {
                                        className: "card-title"
                                      }, Caml_array.caml_array_get(broadcasterObject, 0)), React.createElement("p", {
                                        className: "card-text"
                                      }, "Some quick example text to build on the card title and make up the bulk of the card's content."), React.createElement("a", {
                                        className: "btn btn-primary",
                                        href: "#"
                                      }, "Open modal"))) : React.createElement("div", undefined));
            }),
          /* initialState */(function (param) {
              return /* record */[/* data : record */[
                        /* id */"",
                        /* login */"",
                        /* display_name */"",
                        /* account_type */"",
                        /* broadcaster_type */"",
                        /* description */"",
                        /* profile_image_url */"",
                        /* offline_image_url */"",
                        /* view_count */0,
                        /* email */""
                      ]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* data */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Decode = Decode;
exports.component = component;
exports.make = make;
/* component Not a pure module */
