// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LogIn$ReactTemplate = require("./views/LogIn.bs.js");
var Dashboard$ReactTemplate = require("./views/Dashboard.bs.js");
var JudgementPage$ReactTemplate = require("./views/JudgementPage.bs.js");

function decodeStreamer(json) {
  return /* record */[
          /* to_name */Json_decode.field("to_name", Json_decode.string, json),
          /* to_id */Json_decode.field("to_id", Json_decode.string, json),
          /* followed_at */Json_decode.field("followed_at", Json_decode.string, json)
        ];
}

function decodeUser(json) {
  return /* record */[
          /* total */Json_decode.field("total", Json_decode.$$int, json),
          /* data */Json_decode.field("data", (function (param) {
                  return Json_decode.array(decodeStreamer, param);
                }), json)
        ];
}

var Decode = /* module */[
  /* decodeStreamer */decodeStreamer,
  /* decodeUser */decodeUser
];

function toPage(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "dashboard" : 
          return /* Dashboard */1;
      case "judgement" : 
          if (match[1]) {
            return /* Dashboard */1;
          } else {
            return /* JudgementPage */2;
          }
      case "login" : 
          if (match[1]) {
            return /* Dashboard */1;
          } else {
            return /* LogIn */0;
          }
      default:
        return /* Dashboard */1;
    }
  } else {
    return /* Dashboard */1;
  }
}

function toUrl(page) {
  switch (page) {
    case 0 : 
        return "login";
    case 1 : 
        return "dashboard";
    case 2 : 
        return "judgement";
    
  }
}

var Mapper = /* module */[
  /* toPage */toPage,
  /* toUrl */toUrl
];

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = function (param) {
                return ReasonReact.Router[/* watchUrl */2]((function (url) {
                              return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(0, [toPage(url)]));
                            }));
              };
              Curry._1(self[/* onUnmount */4], (function (param) {
                      return ReasonReact.Router[/* unwatchUrl */3](watcherID(/* () */0));
                    }));
              fetch("https://api.twitch.tv/helix/users/follows?from_id=114494398", Fetch.RequestInit[/* make */0](undefined, {
                                "Client-ID": "re6wrq92zpvgqndlc8mokgr97j09l9"
                              }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                          return prim.json();
                        })).then((function (json) {
                        var decodedJSON = decodeUser(json);
                        return Promise.resolve(Curry._1(self[/* send */3], /* SetData */Block.__(1, [decodedJSON])));
                      })).catch((function (_err) {
                      return Promise.resolve(Curry._1(self[/* send */3], /* FailedToFetch */Block.__(2, ["Twitch API"])));
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var match$1 = self[/* state */1][/* loggedIn */1];
              var tmp;
              switch (match) {
                case 0 : 
                    tmp = ReasonReact.element(undefined, undefined, LogIn$ReactTemplate.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = match$1 ? ReasonReact.element(undefined, undefined, Dashboard$ReactTemplate.make(self[/* state */1][/* followData */3][/* data */1], /* array */[])) : ReasonReact.element(undefined, undefined, LogIn$ReactTemplate.make(/* array */[]));
                    break;
                case 2 : 
                    tmp = match$1 ? ReasonReact.element(undefined, undefined, JudgementPage$ReactTemplate.make(/* array */[])) : ReasonReact.element(undefined, undefined, LogIn$ReactTemplate.make(/* array */[]));
                    break;
                
              }
              return React.createElement("div", {
                          className: "container-fluid"
                        }, React.createElement("nav", {
                              className: "navbar navbar-expand-lg navbar-light bg-light"
                            }, React.createElement("a", {
                                  className: "navbar-brand",
                                  href: "#"
                                }, "Navbar"), React.createElement("div", {
                                  className: "collapse navbar-collapse",
                                  id: "navbarSupportedContent"
                                }, React.createElement("ul", {
                                      className: "navbar-nav mr-auto"
                                    }, React.createElement("li", {
                                          className: "nav-item active"
                                        }, React.createElement("a", {
                                              className: "nav-link",
                                              href: "#"
                                            }, "Home", React.createElement("span", {
                                                  className: "sr-only"
                                                }, "(current)"))), React.createElement("li", {
                                          className: "nav-item"
                                        }, React.createElement("a", {
                                              className: "nav-link",
                                              href: "#"
                                            }, "Link")), React.createElement("li", {
                                          className: "nav-item dropdown"
                                        }, React.createElement("div", {
                                              className: "dropdown-menu"
                                            }, React.createElement("a", {
                                                  className: "dropdown-item",
                                                  href: "#"
                                                }, "action"), React.createElement("a", {
                                                  className: "dropdown-item",
                                                  href: "#"
                                                }, "Another action"), React.createElement("div", {
                                                  className: "dropdown-divider"
                                                }), React.createElement("a", {
                                                  className: "dropdown-item",
                                                  href: "#"
                                                }, "Yet another action")))))), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(0, [/* LogIn */0]));
                                        })
                                    }, "Log In")), React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(0, [/* Dashboard */1]));
                                        })
                                    }, "Dashboard")), React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(0, [/* JudgementPage */2]));
                                        })
                                    }, "Judgement Page"))), tmp);
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* route */toPage(ReasonReact.Router[/* dangerouslyGetInitialUrl */4](/* () */0)),
                      /* loggedIn */true,
                      /* credentials : tuple */[
                        "",
                        ""
                      ],
                      /* followData : record */[
                        /* total */0,
                        /* data : array */[]
                      ]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    var route = action[0];
                    ReasonReact.Router[/* replace */1](toUrl(route));
                    return /* Update */Block.__(0, [/* record */[
                                /* route */route,
                                /* loggedIn */state[/* loggedIn */1],
                                /* credentials */state[/* credentials */2],
                                /* followData */state[/* followData */3]
                              ]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* route */state[/* route */0],
                                /* loggedIn */state[/* loggedIn */1],
                                /* credentials */state[/* credentials */2],
                                /* followData */action[0]
                              ]]);
                case 2 : 
                    var fetchLocation = action[0];
                    return /* SideEffects */Block.__(1, [(function (_self) {
                                  console.log("Error, failed to fetch data from " + (fetchLocation + "."));
                                  return /* () */0;
                                })]);
                
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Decode = Decode;
exports.Mapper = Mapper;
exports.component = component;
exports.make = make;
/* component Not a pure module */
