// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LogIn$ReactTemplate = require("./views/LogIn.bs.js");
var Dashboard$ReactTemplate = require("./views/Dashboard.bs.js");
var JudgementPage$ReactTemplate = require("./views/JudgementPage.bs.js");

function toPage(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "dashboard" : 
          return /* Dashboard */1;
      case "judgement" : 
          if (match[1]) {
            return /* Dashboard */1;
          } else {
            return /* JudgementPage */2;
          }
      case "login" : 
          if (match[1]) {
            return /* Dashboard */1;
          } else {
            return /* LogIn */0;
          }
      default:
        return /* Dashboard */1;
    }
  } else {
    return /* Dashboard */1;
  }
}

function toUrl(page) {
  switch (page) {
    case 0 : 
        return "login";
    case 1 : 
        return "dashboard";
    case 2 : 
        return "judgement";
    
  }
}

var Mapper = /* module */[
  /* toPage */toPage,
  /* toUrl */toUrl
];

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = function (param) {
                return ReasonReact.Router[/* watchUrl */2]((function (url) {
                              return Curry._1(self[/* send */3], /* ChangeRoute */[toPage(url)]);
                            }));
              };
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */3](watcherID(/* () */0));
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var tmp;
              switch (match) {
                case 0 : 
                    tmp = ReasonReact.element(undefined, undefined, LogIn$ReactTemplate.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = ReasonReact.element(undefined, undefined, Dashboard$ReactTemplate.make(/* array */[]));
                    break;
                case 2 : 
                    tmp = ReasonReact.element(undefined, undefined, JudgementPage$ReactTemplate.make(/* array */[]));
                    break;
                
              }
              return React.createElement("div", undefined, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[/* LogIn */0]);
                                        })
                                    }, "Log In")), React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[/* Dashboard */1]);
                                        })
                                    }, "Dashboard")), React.createElement("li", undefined, React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[/* JudgementPage */2]);
                                        })
                                    }, "Judgement Page"))), tmp);
            }),
          /* initialState */(function (param) {
              return /* record */[/* route */toPage(ReasonReact.Router[/* dangerouslyGetInitialUrl */4](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              var route = action[0];
              ReasonReact.Router[/* replace */1](toUrl(route));
              return /* Update */Block.__(0, [/* record */[/* route */route]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Mapper = Mapper;
exports.component = component;
exports.make = make;
/* component Not a pure module */
